### ISSUE TITLE
Maybe typo?

### ISSUE THREAD

**Issue by toku-sa-n** [rust-osdev/volatile#17]
From the doc of `Volatile::new`
>While it is possible to construct Volatile instances from arbitrary values (including non-reference values), most of the methods are only available when the wrapped type is a reference. The only reason that we don't forbid non-reference types in the constructor functions is that the Rust compiler does not support trait bounds on generic const functions yet. When this becomes possible, we will release a new version of this library with removed support for non-references. For these reasons it is not recommended to use the Volatile type only with references.

Should the last sentence be "For these reasons it is recommended to use the `Volatile` type only with references."? (remove *not*)

**Comment by phil-opp** [comment]
Good catch! Mind sending in a quick PR to fix this?

**Comment by phil-opp** [comment]
(Sorry about closing this directly, that was completely accidental. Thanks for the fix in https://github.com/rust-osdev/volatile/pull/18!)
