### ISSUE TITLE
ReadWrite type is redundant

### ISSUE THREAD

**Issue by blacksmithgu** [rust-osdev/volatile#2]
The `ReadWrite` type is functionally equivalent to the `Volatile` type. Is there any reason for having this, or is it for consistency's sake with `ReadOnly` and `WriteOnly` (in case the semantics of `Volatile` change)?

**Comment by phil-opp** [comment]
It's just for consistency. When you just need a volatile wrapper, the name `Volatile` makes more sense than `ReadWrite`. However, when using `ReadOnly` and `WriteOnly` (e.g. to describe memory mapped hardware registers), the name `ReadWrite` fits better.

I agree that a separate `ReadWrite` struct is redundant. We should make `ReadWrite` a type alias for `Volatile` instead (`pub type ReadWrite = Volatile;`).

**Comment by blacksmithgu** [comment]
Ah, that would fix it nicely!
