### ISSUE TITLE
Idea: Provide atomic volatile types

### ISSUE THREAD

**Issue by phil-opp** [rust-osdev/volatile#30]
Proposed by @mkroening in https://github.com/rust-osdev/volatile/pull/29#issuecomment-1398132992.

**Comment by mkroening** [comment]
My initial thought was on using `AtomicPtr` to atomically move the pointer between cores. This would model `Option<&mut T>` or `Option<AtomicPtrSend>`. Thinking about it, I can't find much use for that over a `SpinMutex<AtomicPtrSend>`, though.

Using atomic types for MMIO data would have the existing issue regarding references and `dereferencable`. One could use intrinsics like [`core::intrinsics::atomic_load_relaxed`](https://doc.rust-lang.org/nightly/core/intrinsics/fn.atomic_load_relaxed.html), but intrinsics are never intended to be stabilized.

**Comment by phil-opp** [comment]
Ah, thanks for clarifying! In that case, let's postpone this idea for now untl a potential use-case comes up.

> Using atomic types for MMIO data would have the existing issue regarding references and `dereferencable`. One could use intrinsics like [`core::intrinsics::atomic_load_relaxed`](https://doc.rust-lang.org/nightly/core/intrinsics/fn.atomic_load_relaxed.html), but intrinsics are never intended to be stabilized.

Yeah, good point.

**Comment by Freax13** [comment]
Related: https://github.com/rust-lang/unsafe-code-guidelines/issues/347

**Comment by phil-opp** [comment]
Also related: https://rust-lang.zulipchat.com/#narrow/stream/136281-t-lang.2Fwg-unsafe-code-guidelines/topic/volatile.20atomic.20in.20Rust.3F
