### ISSUE TITLE
This crate is currently unsound due to spurious reads 

### ISSUE THREAD

**Issue by matthunz** [rust-osdev/volatile#39]
As pointed out in https://github.com/japaric/vcell/issues/10, crates like this that use references to mmio are unsound.

I propose a new design that only stores raw pointers to prevent this behavior.
We could then initialize the cell using [`addr_of_mut`](https://doc.rust-lang.org/stable/std/ptr/macro.addr_of_mut.html) to avoid any creation of references before that data is initialized.
```rust
pub struct VolatileCell<T> {
    ptr: *mut T,
}

impl<T> VolatileCell<T> {
    pub fn new(ptr: *mut T) -> Self {
        Self { ptr }
    }

    pub fn get(&self) -> T
    where
        T: Copy,
    {
        unsafe { self.ptr.read_volatile() }
    }

    pub fn get_mut(&self) -> T
    where
        T: Copy,
    {
        unsafe { self.ptr.read_volatile() }
    }
}
```

**Comment by phil-opp** [comment]
Thanks for reporting! We are currently working on a new interface based on raw pointers in https://github.com/rust-osdev/volatile/pull/29. It still requires some polishing, but I hope that it will be ready soon.
