### ISSUE TITLE
Implement copy for volatile?

### ISSUE THREAD

**Issue by BuggStream** [rust-osdev/volatile#9]
So I have been following the 'Writing an OS in Rust' guide. And while I was experimenting and reading through the code I noticed that `Copy` hasn't been implemented for `Volatile`.

This could be useful when writing code:

```rust
impl<T: Copy> Copy for Volatile<T> {
    // Empty.
}
```

After this the new line function for the VGA buffer can be implemented as follows:

```rust
fn new_line(&mut self) {
    &self.buffer.chars.copy_within(1.., 0);
        
    self.clear_row(BUFFER_HEIGHT - 1);
    self.column_position = 0;
}
```

Now I did notice that `copy_within` uses the normal `ptr::copy` instead of [volatile_copy_memory](https://doc.rust-lang.org/core/intrinsics/fn.volatile_copy_memory.html). Is this a potential issue?

Anyway let me know if you want to add this, if so I will make a short MR.

**Comment by videah** [comment]
See https://github.com/embed-rs/volatile/pull/6#issuecomment-433612911 and https://github.com/embed-rs/volatile/pull/5#issuecomment-353783786 as to why this hasn't been done yet.

I would like to see VolatileArray be implemented, is that possible now? @phil-opp

**Comment by BuggStream** [comment]
> See [#6 (comment)](https://github.com/embed-rs/volatile/pull/6#issuecomment-433612911) and [#5 (comment)](https://github.com/embed-rs/volatile/pull/5#issuecomment-353783786) as to why this hasn't been done yet.
> 
> I would like to see VolatileArray be implemented, is that possible now? @phil-opp

Oh it seems like I forgot to look at the MRs to check if this was already asked. Sorry about that. Anyway thanks for your answer.

I'd also be interested to know if something like VolatileArray could be useful.

**Comment by phil-opp** [comment]
I _think_ it should be possible to implement `VolatileArray` and `VolatileSlice` types now that we have basic support for const generics in Rust, but I'm not 100% sure.

**Comment by phil-opp** [comment]
The new v0.5.0 release includes both a `VolatilePtr` type that implements `Copy` and (unstable) methods for accessing slices and arrays.
